# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaichun Mo's Personal Blog
email: daeduomkch [at] gmail.com
description: This is Kaichun Mo's Personal Blog. Thoughts, ideas and founds are came out to be shared!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daerduoCarey.github.io" # the base hostname & protocol for your site
twitter_username: KaichunMo
github_username:  daerduoCarey

# Build settings
markdown: kramdown
